
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: financeguard-api

    ports:
      - "8000:8000"

    restart: unless-stopped

  streamlit:

    build:
      context: .
      dockerfile: Dockerfile.streamlit

    container_name: financeguard-streamlit

    ports:
      - "8501:8501"

    depends_on:
      - api

    restart: unless-stopped